modLoader="javafml"
loaderVersion="47,)"
license="All Rights Reserved, DragN0007"
#issueTrackerURL="https://discord.gg/2WznNTtVac"
[[mods]]
modId="dragnlivestock"
version="${2.5}"
displayName="DragN's Livestock Overhaul!"
logoFile="livestock_overhaul_logo.png"
authors="DragN0007"
description='''
An overhaul for livestock & farm animals!
'''
[[dependencies.dragnlivestock]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.dragnlivestock]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.dragnlivestock]]
modId="geckolib"
mandatory=true
versionRange = "[4.4.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.dragnlivestock]]
modId="patchouli"
mandatory=false
versionRange = "[1.20.1-84,)"
ordering="NONE"
side="BOTH"